### ISSUE TITLE
ValueError: Unknown protocol 'neo4j'

### ISSUE THREAD

**Issue by tilchl** [huichen5796/ma_backend#1]
Is there a reason why you used `py2neo==2021.2.4` even if it is EOL?
I can't get it to run.

I' running it in Docker as recommended by `fastapi`

```dockerfile
FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
COPY ./app/conf /code/app/conf
COPY ./app/lib_build /code/app/lib_build
COPY ./app/lib_save /code/app/lib_save 
COPY ./app/lib_load /code/app/lib_load

WORKDIR /code/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
```

```py
{'profile_cryo': 'bolt://db:7687', 'password_cryo': 'test_cryo', 'profile_cpa': 'bolt://db:7687', 'password_cpa': 'test_cpa'}
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/code/app/main.py", line 30, in <module>
    from data_to_db import FeedIntoNeo4j
  File "/code/app/data_to_db.py", line 8, in <module>
    GRAPH_CRYO = connect_to_db('cryo')
  File "/code/app/lib_save/connect_to_db.py", line 12, in connect_to_db
    graph = Graph(data['profile_cryo'], password=data['password_cryo'])
  File "/usr/local/lib/python3.9/site-packages/py2neo/database.py", line 288, in __init__
    self.service = GraphService(profile, **settings)
  File "/usr/local/lib/python3.9/site-packages/py2neo/database.py", line 119, in __init__
    self._connector = Connector(profile, **connector_settings)
  File "/usr/local/lib/python3.9/site-packages/py2neo/client/__init__.py", line 948, in __init__
    self._initial_routers = [ConnectionProfile(profile)]
  File "/usr/local/lib/python3.9/site-packages/py2neo/__init__.py", line 176, in __init__
    self._apply_env_vars()
  File "/usr/local/lib/python3.9/site-packages/py2neo/__init__.py", line 220, in _apply_env_vars
    self._apply_uri(NEO4J_URI)
  File "/usr/local/lib/python3.9/site-packages/py2neo/__init__.py", line 232, in _apply_uri
    self._apply_scheme(parsed.scheme)
  File "/usr/local/lib/python3.9/site-packages/py2neo/__init__.py", line 249, in _apply_scheme
    self._apply_settings(protocol=protocol, secure=False, verify=True)
  File "/usr/local/lib/python3.9/site-packages/py2neo/__init__.py", line 266, in _apply_settings
    self._apply_protocol(protocol)
  File "/usr/local/lib/python3.9/site-packages/py2neo/__init__.py", line 297, in _apply_protocol
    raise ValueError("Unknown protocol %r" % protocol)
ValueError: Unknown protocol 'neo4j'
```

**Comment by huichen5796** [comment]
Hi Lukas, 

In fact, just now I just knew that py2neo was outdated. I might find some time to migrate it to the neo4j library (maybe this weekend).

I noticed that you used `bolt://` connection, have you tried using `neo4j://`?

**Comment by tilchl** [comment]
Hey,

i also tried `neo4j` but it's the same outcome
```py
ValueError: Unknown protocol 'neo4j'
```
which is odd.
Did you do some last minute changes on the AWS instance?

**Comment by huichen5796** [comment]
Hii, If you redeployed the neo4j database by yourself, you maybe should done something like here -> https://github.com/huichen5796/2023-masterarbeit-frontend/issues/10

maybe you need to change neo4j.conf and then change password on website firstly after deploy the db

for deployment of backend I didn't do anything special -> https://github.com/huichen5796/2023-masterarbeit-frontend/issues/11

**Comment by huichen5796** [comment]
Hey, klappt jetzt alles? Oder ich sollte py2neo auf neo4j Library ändern?

**Comment by tilchl** [comment]
Ich habe es nach der Anleitung gemacht, leider bleibt der Fehler bestehen.

Wenn du es zeitlich schaffst auf die neo4j library zu wechseln, wäre das super.

**Comment by huichen5796** [comment]
alles klar, kein Problem, ich würde dann an diesem Wochenende wechseln.

**Comment by huichen5796** [comment]
Hii, it has been changed from py2neo to neo4j. I tested that most of the functionality works fine, but when writing files in large batches I get the following error

```
INFO:     127.0.0.1:60994 - "GET /feedInNeo/?data_type=PostData&file_name=EQ20231005A-75D-4.txt&data_store=data_store HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ma_backend\main.py", line 186, in feedInNeo
    return FeedIntoNeo4j(data_type, f'{data_store}/{data_type}/{file_name}').feed_to_neo4j()
  File "D:\ma_backend\data_to_db.py", line 67, in feed_to_neo4j
    return dict_to_neo_postdata(GRAPH_CRYO_SESSION, loaded_data)
  File "D:\ma_backend\lib_save\dict_to_neo_postdata.py", line 8, in dict_to_neo_postdata
    session.run(
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\work\session.py", line 313, in run
    self._auto_result._run(
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\work\result.py", line 181, in _run
    self._attach()
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\work\result.py", line 301, in _attach
    self._connection.fetch_message()
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_common.py", line 178, in inner
    func(*args, **kwargs)
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_bolt.py", line 847, in fetch_message
    tag, fields = self.inbox.pop(
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_common.py", line 72, in pop
    self._buffer_one_chunk()
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_common.py", line 56, in _buffer_one_chunk
    receive_into_buffer(
  File "C:\Users\chen1\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_common.py", line 323, in receive_into_buffer
    buffer.data += bytearray(end - len(buffer.data))
BufferError: Existing exports of data: object cannot be re-sized
```

This error can be easily reproduced by writing about 30 postdata files to the database at the same time. I guess it may be because the db is overloaded, but strangely there is no such problem when using py2neo. I began to speculate that it was because a new session was opened when each postdata file was written. Too many sessions caused overload, so I tried to write all postdata in the same session, but the situation became worse. 

But please test whether it can be deployed on docker now. Then we can further discuss the issue of overload.

**Comment by huichen5796** [comment]
hii, does it works now?

**Comment by tilchl** [comment]
thank you so much, now it is connecting as expected.


but now i get this in the frontend
```
Connection Check:

Success: Connected to Database 'cryo'.

{
  "Node": {},
  "Relation": {}
}

Error: Loss Connection to Database 'cpa'.
```

is this maybe an issue with seeding?

**Comment by huichen5796** [comment]
hi, this part returns the results of querying the number of nodes and relationships in the database. here is the code, you can found them in `/lib_build/build_db.py` in backend
```
node_counts = session.run("MATCH (n) RETURN DISTINCT labels(n) AS label, count(*) AS count").data()
relationship_counts = session.run("MATCH ()-[r]->() RETURN DISTINCT type(r) AS type, count(*) AS count").data()
```
**I think there is a problem with the communication with the cpa database.** You can found the error log in `/log/log_build.txt` like 
```
xxxxxx ERROR ON QUERY ALL: xxxx
```

I forgot to mention in the paper that the database needs to be initialized (adding necessary unique constraints) when establishing the database. You can try to use the following code to see if the error still exists after initialization:
```python
from main import *

cleanDatabase('cpa') # delete all things in db
initDatabase('cpa') # add necessary unique constraints for nodes
cleanDatabase('cryo') 
initDatabase('cryo')
```

it should look like this in frontend when db no problem is:
![image](https://github.com/huichen5796/2023-masterarbeit-backend/assets/79353997/4b74323d-abcc-499a-920b-0f3f89e82998)

**Comment by huichen5796** [comment]
hi Lukas, klappt es jetzt alles?

**Comment by tilchl** [comment]
Thank you hui, i just placed the init in the main

Now i get this error

```py
Connection Check:

Success: Connected to Backend.

Error: Loss Connection to Data Store data_store.

Data Store Integrity Check:

Success: Created Subfolder /CPA.

Success: Created Subfolder /Experiment.

Success: Created Subfolder /PreData.

Success: Created Subfolder /PostData.

Success: Created Subfolder /Process.
```

**Comment by huichen5796** [comment]
Hi Lukas, it is a bug when the backend was connected by front end at the first time.

relevant code is in `lib/build_data_store.py`. Every time the frontend connects to the backend, it deletes the temporary folder used to store user uploaded files and then recreates it. I forgot to create this folder once when the backend starts, so it will try to delete a non-existent folder when connecting with frontend for the first time, causing an error. I think it only happens the first time because my shit mountain code checks for this temp file multiple times and tries to create it. You can see that eventually the subfolders of this folder exist correctly at the end. *So refreshing the Webseite will fix this error and it won't happen again. I think*

```

def delete_folder(self):
        try:
            base_dir = os.getcwd()
            data_store_dir = os.path.join(base_dir, self.dir_name)
            shutil.rmtree(data_store_dir)
            with open('log/log_build.txt', 'a+') as file:
                        file.write(
                            f"{datetime.datetime.now()} SUCCESS Deleted folder: {data_store_dir} \n")
            return 'success'
        except Exception as e:
            with open('log/log_build.txt', 'a+') as file:
                file.write(
                    f"{datetime.datetime.now()} ERROR ON DELETE DATA STORE FOLDER {self.dir_name}: {e} \n")
            return 'error'
```

other unnecessary info about this part:
 this part is relevant to this four router in `main.py`. 

```

@app.get("/buildDataStore/{store_name}")
def buildDataStore(store_name):
    return BuildDataStore(store_name).create_data_store_folder()


@app.get("/deleteDataStore/{store_name}")
def deleteDataStore(store_name):
    return BuildDataStore(store_name).delete_folder()


@app.get("/deleteOneType/")
def deleteOneType(store_name, data_type):
    return BuildDataStore(store_name).delete_one_type(data_type)


@app.get("/checkIntegrity/")
def checkIntegrity(store_name, data_type):
    todo = data_type.split(',')
    response = {}
    for file in todo:
        response[file] = BuildDataStore(store_name).create_one_type(file)
    return responds
```

Every time you connect to the backend, the temporary folder ‘data_store’ is *deleted and recreated*, to be ready to categorize the files coming from the frontend. I don't remember why I didn't choose to clear but just deleted everything and rebuilt. :-) This temporary folder is structured as follows:

```
data_store/
         |___CPA
         |___Experiment
         |___Process
         |___PreData
         |___PostData
```

Once the entire folder is  deleted and recreated by connecting with frontend, all subfolders are checked one by one to see if they were created correctly.

The corresponding component of the front end is `unit-check-backend`
